Dsl for ViewPager
Inkremental/anvil pull request #76
Opened 2020-06-15 15:24 UTC by sgrekov

This PR adds the possibility to create and fill ViewPager from dsl

2020-06-15 17:53 UTC, r4zzz4k requested changes
Let's not put any manually written code to `gen-` sourceSets to avoid confusing. I've separated generated code into its own source set specifically to be able to delete `gen-*` directories entirely without fear of missing some important stuff :)

2020-06-15 21:21 UTC, sgrekov commented
> Let's not put any manually written code to gen- sourceSets to avoid confusing. I've separated generated code into its own source set specifically to be able to delete gen-* directories entirely without fear of missing some important stuff :)

Hmm, true, my bad. But this also means that _CustomSupportV4Setter_ shouldn't be there either. 
If you don't mind will move it in this PR

2020-06-16 10:03 UTC, r4zzz4k approved these changes

2020-06-16 12:15 UTC, Mishkun approved these changes

2020-06-16 12:20 UTC, merged